export const templateImagesPaths = [
  //this object contains the paths of the static template images that will be used to display template images in the Home page.
  {
    id: 1,
    name: 'Drag 1',
    imageSource: '/res1.PNG',
  },
  {
    id: 2,
    name: 'Drag 2',
    imageSource: '/res2.PNG',
  },
]

export const stateNames = [
  'Andhra Pradesh',
  'Andaman and Nicobar Islands',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadar and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Lakshadweep',
  'Puducherry',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
]
